namespace: ondemand-dev

bases:
- ../../base

resources:
- ns.yaml
- ingress.yaml

patchesStrategicMerge:
- ondemand-patch.yaml

secretGenerator:
- name: auth
  files:
  - etc/.secrets/htpasswd
  - etc/.secrets/ldap.password
  - etc/.secrets/oidc_client_id
  - etc/.secrets/oidc_client_secret
  - etc/.secrets/oidc_crypto_passphrase
  - etc/.secrets/sp-cert.pem
  - etc/.secrets/sp-key.pem
- name: certs
  files:
  - etc/.secrets/ondemand-dev.key
  - etc/.secrets/ondemand-dev.crt
  - etc/.secrets/ondemand-dev.intermediates

configMapGenerator:
- name: ood-config
  files:
  - etc/ood_portal.yml
  - etc/sdf_cluster.yml
  - etc/sdf_desktop.yml
- name: pun-html
  files:
  - etc/pun.env
  - etc/missing_home_directory.html

images:
- name: slaclab/slac-ondemand
  newTag: "latest"
  #newTag: saml2
- name: slaclab/sdf-docs
  newTag: "20220308.21"
