namespace: dev

bases:
- ../../base

resources:
- ns.yaml
- ingress.yaml
- sdf-home-pvc.yaml
- ondemand-logs-pvc.yaml

patchesStrategicMerge:
- ondemand-patch.yaml

secretGenerator:
- name: certs
  files:
  - etc/.secrets/ondemand-dev.key
  - etc/.secrets/ondemand-dev.crt
  - etc/.secrets/ondemand-dev.intermediates

configMapGenerator:
- name: ood-config
  files:
  - etc/ood_portal.yml
  - etc/sdf_cluster.yml
  - etc/rubin_interactive_cluster.yaml
  - etc/sdf_desktop.yml
- name: pun-html
  files:
  - etc/pun.env
  - etc/missing_home_directory.html
- name: motd
  options:
    disableNameSuffixHash: true
  files:
  - etc/motd

images:
- name: slaclab/slac-ondemand
  newTag: "latest"
- name: slaclab/sdf-docs
  newTag: "20220308.21"
