apiVersion: apps/v1
kind: Deployment
metadata:
  name: ondemand
spec:
  template:
    spec:
      nodeSelector:
        edu.stanford.slac.sdf.slurm: 'true'
      containers:
      - name: ondemand
        imagePullPolicy: Always
        # command: [ "bash", "-c", "sleep infinity" ]
        env:
        - name: OOD_SERVERNAME
          value: ondemand-dev.slac.stanford.edu
        - name: OOD_HOST_REGEX
          value: '\(rome|psc|tur|volt|ampt\)\\d\{3,4\}\\.slac\\.stanford\\.edu'
        - name: OOD_DEFAULT_SSHHOST
          value: sdf.slac.stanford.edu
        #- name: OOD_USER_MAP_CMD
        #  value: /opt/ood/ood_auth_map/bin/ood_auth_map.regex --regex='^(.*)@slac.stanford.edu$' 
        ## saml2
        #- name: OOD_AUTH_METHOD
        #  value: shib
        #- name: SHIB_SERVERNAME
        #  value: adfs.slac.stanford.edu
        ### LDAP
        #- name: OOD_AUTH_LDAPURL
        #  value: ldaps://ldap-ad.slac.stanford.edu:636/DC=win,DC=slac,DC=Stanford,DC=edu?sAMAccountName?sub?(objectclass=person)(objectcategory=user)
        #- name: OOD_AUTH_LDAPGROUPATTR
        #  value: gidNumber
        #- name: OOD_AUTH_LDAPBINDDN
        #  value: CN=osmaint,OU=Service-Accounts,OU=SCS,DC=win,DC=slac,DC=stanford,DC=edu
        #- name: OOD_AUTH_LDAPBINDPASSWORD
        #  valueFrom:
        #    secretKeyRef:
        #      name: auth
        #      key: ldap.password
        - name: OIDC_CRYPTO_PASSPHRASE
          $patch: delete
        # raw
        - name: OOD_AUTH_METHOD
          value: raw
        - name: OOD_AUTH_RAW
          value: RewriteRule .* - [E=OOD_AUTH_USER:%{HTTP:x-vouch-idp-claims-name}] 
        - name: USER_ENV
          value: OOD_AUTH_USER
        # OIDC
        #- name: OIDC_CACHE_TYPE
        #  value: file
        #- name: OIDC_CACHE_DIR
        #  value: /sdf/sw/ood/dev/cache
        #- name: OIDC_PROVIDER_ISSUER
        #  value: https://dex.slac.stanford.edu
        #- name: OIDC_PROVIDER_METADATA_URL
        #  value: https://dex.slac.stanford.edu/.well-known/openid-configuration
        #- name: OIDC_CLIENT_ID
        #  valueFrom:
        #    secretKeyRef:
        #      name: auth
        #      key: oidc_client_id
        #- name: OIDC_CLIENT_SECRET
        #  valueFrom:
        #    secretKeyRef:
        #      name: auth
        #      key: oidc_client_secret
        #- name: OIDC_SCOPE
        #  value: openid email profile 
        #- name: OIDC_REMOTE_USER_CLAIM
        #  value: email
        #- name: OIDC_REDIRECT
        #  value: oidc
        - name: DEBUG
          value: "1"
        volumeMounts:
        #- name: oidc-cache
        #  mountPath: /var/cache/httpd/mod_auth_openidc/cache
        # general filesystems
        - name: sdf
          mountPath: /sdf/
        # support infra sw
        - name: slurm
          mountPath: /opt/slurm/
        # apps
        #- name: slac-ood-jupyter
        #  mountPath: /var/www/ood/apps/sys/slac-ood-jupyter
        #- name: ood-desktop-config
        #  mountPath: /etc/ood/config/apps/bc_desktop/
        #  readOnly: true
        #- name: slac-ood-desktop
        #  mountPath: /var/www/ood/apps/sys/bc_desktop
        #- name: slac-ood-matlab
        #  mountPath: /var/www/ood/apps/sys/slac-ood-matlab
        #- name: slac-ood-cryosparc
        #  mountPath: /var/www/ood/apps/sys/slac-ood-cryosparc
        # logs
        - name: dashboard-logs
          mountPath: /var/www/ood/apps/sys/dashboard/log
        - name: activejobs-logs
          mountPath: /var/www/ood/apps/sys/activejobs/log
        - name: nginx-logs
          mountPath: /var/log/ondemand-nginx/
        # docs
        - name: sdf-docs
          mountPath: /var/www/ood/public/doc/
          readOnly: true
        # customisation
        - name: motd
          mountPath: /etc/motd
          subPath: motd
        - name: pun-html
          mountPath: /etc/ood/config/pun/html/
        - name: pun-html
          mountPath: /etc/ood/config/apps/dashboard/env
          subPath: pun.env
      - name: sdf-docs 
        image: slaclab/sdf-docs
        resources:
          limits:
            ephemeral-storage: 100Mi
          requests:
            ephemeral-storage: 100Mi
        env:
        - name: http_proxy
          value: http://squid.slac.stanford.edu:3128
        - name: https_proxy
          value: http://squid.slac.stanford.edu:3128
        - name: no_proxy
          value: .slac.stanford.edu
        - name: SLAC_SDF_DOCS_UPDATE_INTERVAL
          value: "300"
        volumeMounts: 
        - mountPath: /sdf-docs
          name: sdf-docs
      volumes:
      - name: sdf-docs
        emptyDir: {}
      - name: motd
        configMap:
          name: motd
          items:
          - key: motd
            path: motd
      - name: ood-clusterd-config
        configMap:
          name: ood-config
          items:
          - key: sdf_cluster.yml
            path: sdf.yml
      # general filesystems
      # kinda nasty....
      - name: sdf
        hostPath:
          path: /sdf/
      # support infra sw
      - name: munge-socket
        hostPath:
          path: /var/run/munge
      - name: slurm
        hostPath:
          path: /opt/slurm
      - name: slurm-config
        hostPath:
          path: /run/slurm/conf/
      # ood apps
      #- name: slac-ood-jupyter
      #  hostPath:
      #    path: /tmp/sdf/sw/ood/dev/apps/sys/slac-ood-jupyter/
      #    type: Directory
      #- name: ood-desktop-config
      #  configMap:
      #    name: ood-config
      #    items:
      #    - key: sdf_desktop.yml
      #      path: sdf.yml
      #- name: slac-ood-desktop
      #  hostPath:
      #    path: /tmp//sdf/sw/ood/dev/apps/sys/slac-ood-desktop/
      #    type: Directory
      #- name: slac-ood-matlab
      #  hostPath:
      #    path: /tmp/sdf/sw/ood/dev/apps/sys/slac-ood-matlab/
      #    type: Directory
      #- name: slac-ood-cryosparc
      #  hostPath:
      #    path: /tmp/sdf/sw/ood/dev/apps/sys/slac-ood-cryosparc/
      #    type: Directory
      # logs
      - name: nginx-logs
        hostPath:
          path: /tmp/sdf/sw/ood/dev/logs/ondemand-nginx
      - name: dashboard-logs
        hostPath:
          path: /tmp//sdf/sw/ood/dev/logs/dashboard
      - name: activejobs-logs
        hostPath:
          path: /tmp//sdf/sw/ood/dev/logs/activejobs
      - name: apache-logs
        hostPath:
          path: /tmp//sdf/sw/ood/dev/logs/httpd
