apiVersion: apps/v1
kind: Deployment
metadata:
  name: ondemand
spec:
  template:
    spec:
      nodeSelector:
        edu.stanford.slac.sdf.slurm: 'true'
      dnsConfig:
        searches:
          - sdf.slac.stanford.edu
          - slac.stanford.edu
      containers:
      - name: ondemand
        imagePullPolicy: Always
        # command: [ "bash", "-c", "sleep infinity" ]
        env:
        - name: OOD_SERVERNAME
          value: s3df-dev.slac.stanford.edu
        - name: OOD_HOST_REGEX
          value: '\(sdfrome\)\\d\{3,4\}\\.sdf\\.slac\\.stanford\\.edu'
        - name: OOD_DEFAULT_SSHHOST
          value: s3dflogin.slac.stanford.edu
        - name: OIDC_CRYPTO_PASSPHRASE
          $patch: delete
        - name: OOD_AUTH_METHOD
          value: raw
        - name: OOD_AUTH_RAW
          value: RewriteRule .* - [E=OOD_AUTH_USER:%{HTTP:x-vouch-idp-claims-name}] 
        - name: USER_ENV
          value: OOD_AUTH_USER
        - name: DEBUG
          value: "0"
        volumeMounts:
        # general filesystems
        - name: sdf
          mountPath: /sdf/
        # support infra sw
        - name: slurm
          mountPath: /opt/slurm/
        # apps
        #- name: slac-ood-jupyter
        #  mountPath: /var/www/ood/apps/sys/slac-ood-jupyter
        #- name: ood-desktop-config
        #  mountPath: /etc/ood/config/apps/bc_desktop/
        #  readOnly: true
        #- name: slac-ood-desktop
        #  mountPath: /var/www/ood/apps/sys/bc_desktop
        #- name: slac-ood-matlab
        #  mountPath: /var/www/ood/apps/sys/slac-ood-matlab
        #- name: slac-ood-cryosparc
        #  mountPath: /var/www/ood/apps/sys/slac-ood-cryosparc
        # logs
        - name: dashboard-logs
          mountPath: /var/www/ood/apps/sys/dashboard/log
        - name: activejobs-logs
          mountPath: /var/www/ood/apps/sys/activejobs/log
        - name: nginx-logs
          mountPath: /var/log/ondemand-nginx/
        # apps
        - name: sdf-docs
          mountPath: /var/www/ood/public/doc/
          readOnly: true
        - name: slac-ood-jupyter
          mountPath: /var/www/ood/apps/sys/slac-ood-jupyter/
          readOnly: true
        # customisation
        - name: motd
          mountPath: /etc/motd
          subPath: motd
        - name: pun-html
          mountPath: /etc/ood/config/pun/html/
        - name: pun-html
          mountPath: /etc/ood/config/apps/dashboard/env
          subPath: pun.env
      - name: sdf-docs 
        image: slaclab/sdf-docs
        resources:
          limits:
            ephemeral-storage: 100Mi
          requests:
            ephemeral-storage: 100Mi
        env:
        - name: http_proxy
          value: http://squid.slac.stanford.edu:3128
        - name: https_proxy
          value: http://squid.slac.stanford.edu:3128
        - name: no_proxy
          value: .slac.stanford.edu
        - name: SLAC_SDF_DOCS_UPDATE_INTERVAL
          value: "300"
        - name: SLAC_SDF_DOCS_VERSION
          value: s3df
        volumeMounts: 
        - mountPath: /sdf-docs
          name: sdf-docs
      - name: slac-ood-jupyter
        image: slaclab/gitclone
        #command: ["/bin/sh","-c","sleep infinity"]
        resources:
          limits:
            ephemeral-storage: 100Mi
          requests:
            ephemeral-storage: 100Mi
        env:
        - name: http_proxy
          value: http://squid.slac.stanford.edu:3128
        - name: https_proxy
          value: http://squid.slac.stanford.edu:3128
        - name: no_proxy
          value: .slac.stanford.edu
        - name: GIT_REPO
          value: https://github.com/slaclab/slac-ood-jupyter.git
        - name: GIT_RELEASE
          value: s3df
        volumeMounts:
        - mountPath: /app
          name: slac-ood-jupyter
      volumes:
      - name: sdf-docs
        emptyDir: {}
      - name: slac-ood-jupyter
        emptyDir: {}
      - name: motd
        configMap:
          name: motd
          items:
          - key: motd
            path: motd
      - name: ood-clusterd-config
        configMap:
          name: ood-config
          items:
          - key: sdf_cluster.yml
            path: sdf.yml
      # general filesystems
      # kinda nasty....
      - name: sdf
        hostPath:
          path: /sdf/
      - name: fs
        hostPath:
          path: /fs/
      # support infra sw
      - name: munge-socket
        hostPath:
          path: /var/run/munge
      - name: slurm
        hostPath:
          path: /opt/slurm
      - name: slurm-config
        hostPath:
          path: /run/slurm/conf/
      # ood apps
      #- name: slac-ood-jupyter
      #  hostPath:
      #    path: /tmp/sdf/sw/ood/dev/apps/sys/slac-ood-jupyter/
      #    type: Directory
      #- name: ood-desktop-config
      #  configMap:
      #    name: ood-config
      #    items:
      #    - key: sdf_desktop.yml
      #      path: sdf.yml
      #- name: slac-ood-desktop
      #  hostPath:
      #    path: /tmp//sdf/sw/ood/dev/apps/sys/slac-ood-desktop/
      #    type: Directory
      #- name: slac-ood-matlab
      #  hostPath:
      #    path: /tmp/sdf/sw/ood/dev/apps/sys/slac-ood-matlab/
      #    type: Directory
      #- name: slac-ood-cryosparc
      #  hostPath:
      #    path: /tmp/sdf/sw/ood/dev/apps/sys/slac-ood-cryosparc/
      #    type: Directory
      # logs
      - name: nginx-logs
        persistentVolumeClaim:
          claimName: nginx-logs
      - name: dashboard-logs
        persistentVolumeClaim:
          claimName: dashboard-logs
      - name: activejobs-logs
        persistentVolumeClaim:
          claimName: activejobs-logs
      - name: apache-logs
        persistentVolumeClaim:
          claimName: apache-logs
