apiVersion: apps/v1
kind: Deployment
metadata:
  name: ondemand
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ondemand
  template:
    metadata:
      labels:
        app: ondemand
    spec:
      containers:
      - name: ondemand
        image: slaclab/slac-ondemand:20200417.0
        imagePullPolicy: Always
        #livenessProbe:
        #  httpGet:
        #    path: /
        #    port: 443
        #  initialDelaySeconds: 5
        #  periodSeconds: 10
        env:
        - name: OOD_SERVERNAME
          value: ondemand-dev.slac.stanford.edu
        - name: OOD_DEFAULT_SSHHOST
          value: sdf.slac.stanford.edu
        - name: OOD_AUTH_METHOD
          value: htpasswd
          #value: ldap
        #- name: OOD_AUTH_LDAPURL
        #  value: ldaps://ldap601.slac.stanford.edu:636/ou=Accounts,dc=slac,dc=stanford,dc=edu 
        - name: OIDC_CRYPTO_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: auth
              key: oidc_crypto_passphrase
        volumeMounts:
        - name: slurm-config
          mountPath: /run/slurm/conf/
          readOnly: true
        - name: munge-socket
          mountPath: /var/run/munge/
        - name: ood-portal-config
          mountPath: /etc/ood/config/portal/
          readOnly: true
        - name: ood-clusterd-config
          mountPath: /etc/ood/config/clusters.d/
          readOnly: true
        #- name: ood-htpasswd
        #  mountPath: /etc/ood/config/htpasswd/
        #  readOnly: true
        - name: ood-certs
          mountPath: /etc/pki/tls/thisserver/
          readOnly: true
        # docs
        - name: sdf-docs
          mountPath: /var/www/ood/public/doc/
          readOnly: true
        # customisation
        - name: pun-html
          mountPath: /etc/ood/config/pun/html/
        - name: pun-html
          mountPath: /etc/ood/config/apps/dashboard/env
          subPath: pun.env
      - name: sdf-docs 
        image: slaclab/sdf-docs
        env:
        - name: http_proxy
          value: http://squid.slac.stanford.edu:3128
        - name: https_proxy
          value: http://squid.slac.stanford.edu:3128
        - name: no_proxy
          value: .slac.stanford.edu
        - name: SLAC_SDF_DOCS_UPDATE_INTERVAL
          value: "300"
        volumeMounts: 
        - mountPath: /sdf-docs
          name: sdf-docs
      volumes:
      - name: sdf-docs
        emptyDir: {}
      - name: ood-portal-config
        configMap:
          name: ood-config
          items:
          - key: ood_portal.yml
            path: ood_portal.yml
      #- name: ood-clusterd-config
      #  configMap:
      #    name: ood-config
      #    items:
      #    - key: sdf_cluster.yml
      #      path: sdf.yml
      #- name: ood-htpasswd
      #  secret:
      #    secretName: auth
      #    defaultMode: 256
      #    items:
      #    - key: htpasswd
      #      path: .htpasswd
      - name: ood-certs
        secret:
          secretName: certs
          defaultMode: 420
      # customisation
      - name: pun-html
        configMap:
          name: pun-html

