
namespace: ondemand-prod

bases:
- ../../base

resources:
- ns.yaml
- ingress.yaml

patchesStrategicMerge:
- ondemand-patch.yaml

secretGenerator:
- name: auth
  files:
  - etc/htpasswd
  - etc/oidc_client_id
  - etc/oidc_client_secret
  - etc/oidc_crypto_passphrase
  - etc/sp-cert.pem
  - etc/sp-key.pem
# doesn't really matter as wer're fronted by the f5s which terminate the ssl
- name: certs
  files:
  - etc/ondemand-dev.key
  - etc/ondemand-dev.crt
  - etc/ondemand-dev.intermediates

configMapGenerator:
- name: ood-config
  files:
  - etc/ood_portal.yml
  - etc/sdf_cluster.yml
  - etc/sdf_desktop.yml
- name: pun-html
  files:
  - etc/pun.env
  - etc/missing_home_directory.html

images:
- name: slaclab/slac-ondemand
  #newTag: '20210817.0'
  newTag: '20211104.0'
