namespace: prod


resources:
- ns.yaml
- ingress.yaml
- sdf-home-pvc.yaml
- ondemand-logs-pvc.yaml
- slurm-service.yaml
- ../../base


secretGenerator:
- files:
  - etc/.secrets/ondemand-dev.key
  - etc/.secrets/ondemand-dev.crt
  - etc/.secrets/ondemand-dev.intermediates
  name: certs

configMapGenerator:
- files:
  - src/linux_host_adapter/launcher.rb
  - src/linux_host_adapter/script_wrapper.erb.sh
  name: linuxhost-adapter-src
- files:
  - 01-s3df.conf=etc/ssh.conf
  name: ssh-config
- files:
  - src/shell/app.js
  name: shell-app-src
- files:
  - src/vnc/vnc.rb
  name: batch-connect-app-vnc-src
  options:
    disableNameSuffixHash: true
- files:
  - etc/ood_portal.yml
  - etc/s3df_desktop.yml
  - etc/nginx_stage.yml
  name: ood-config
  options:
    disableNameSuffixHash: true
- files:
  - etc/clusters.d/s3df_batch.yml
  - etc/clusters.d/rubin_interactive.yml
  - etc/clusters.d/supercdms_interactive.yml
  - etc/clusters.d/iana_interactive.yml
  - etc/clusters.d/suncat_interactive.yml
  - etc/clusters.d/psana_interactive.yml
  - etc/clusters.d/neutrino_interactive.yml
  - etc/clusters.d/mli_interactive.yml
  name: ood-clusters
  options:
    disableNameSuffixHash: true
- files:
  - etc/pun.env
  - etc/missing_home_directory.html
  name: pun-html
- files:
  - etc/motd
  name: motd
  options:
    disableNameSuffixHash: true

images:
- name: slaclab/slac-ondemand
  newTag: 20250528-2128z
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: ondemand-patch.yaml
