apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pun-logs
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashboard-logs
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activejobs-logs
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
