apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pun-log
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashboard-log
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activejobs-log
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
