apiVersion: apps/v1
kind: Deployment
metadata:
  name: ondemand
spec:
  template:
    spec:
      #nodeSelector:
      #  edu.stanford.slac.sdf.slurm: 'true'
#      dnsConfig:
#        options:
#        - name: ndots
#          value: "1"
#        searches:
#        - sdf.slac.stanford.edu
#        - slac.stanford.edu
      containers:
      - name: ondemand
        imagePullPolicy: Always
        # command: [ "bash", "-c", "sleep infinity" ]
        env:
        - name: OOD_SERVERNAME
          value: s3df.slac.stanford.edu
        - name: OOD_HOST_REGEX
          value: '\(sdfrome|sdfmilan|sdfampere|sdfiana|sdfturing|sdfada\)\\d\{3\}\\.sdf\\.slac\\.stanford\\.edu'
        - name: OOD_DEFAULT_SSHHOST
          value: s3dflogin.sdf.slac.stanford.edu
        - name: OIDC_CRYPTO_PASSPHRASE
          $patch: delete
        - name: OOD_AUTH_METHOD
          value: raw
        - name: OOD_AUTH_RAW
          value: RewriteRule .* - [E=OOD_AUTH_USER:%{HTTP:x-vouch-idp-claims-name}] 
        - name: USER_ENV
          value: OOD_AUTH_USER
        - name: DEBUG
          value: "0"
        volumeMounts:
        # source code overrides
        - name: linuxhost-adapter-src
          mountPath: /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.0.3-1/gems/ood_core-0.23.5/lib/ood_core/job/adapters/linux_host/launcher.rb
          subPath: launcher.rb
        - name: linuxhost-adapter-src
          mountPath: /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.0.3-1/gems/ood_core-0.23.5/lib/ood_core/job/adapters/linux_host/templates/script_wrapper.erb.sh
          subPath: script_wrapper.erb.sh
        # ssh config
        - name: ssh-config
          mountPath: /etc/ssh/ssh_config.d/01-s3df.conf
          subPath: 01-s3df.conf
        - name: shell-app-src
          mountPath: /var/www/ood/apps/sys/shell/app.js
          subPath: app.js
        - name: batch-connect-app-vnc-src
          mountPath: /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.0.3-1/gems/ood_core-0.23.5/lib/ood_core/batch_connect/templates/vnc.rb
          subPath: vnc.rb
        # general filesystems
        - name: sdf
          mountPath: /sdf/
        # support infra sw
        - name: slurm
          mountPath: /opt/slurm/
          readOnly: true
        # apps
        - name: ood-desktop-config
          mountPath: /etc/ood/config/apps/bc_desktop/
          readOnly: true
        - name: slac-ood-desktop
          mountPath: /var/www/ood/apps/sys/bc_desktop
        #- name: slac-ood-matlab
        #  mountPath: /var/www/ood/apps/sys/slac-ood-matlab
        # logs
        - name: dashboard-logs
          mountPath: /var/www/ood/apps/sys/dashboard/log
        - name: activejobs-logs
          mountPath: /var/www/ood/apps/sys/activejobs/log
        - name: nginx-logs
          mountPath: /var/log/ondemand-nginx/
        # apps
        - name: slac-ood-jupyter
          mountPath: /var/www/ood/apps/sys/slac-ood-jupyter/
          readOnly: true
        - name: slac-ood-cryosparc
          mountPath: /var/www/ood/apps/sys/slac-ood-cryosparc/
          readOnly: true
        # customisation
        - name: motd
          mountPath: /etc/motd
          subPath: motd
          readOnly: true
        - name: pun-html
          mountPath: /etc/ood/config/pun/html/
          readOnly: true
        - name: pun-html
          mountPath: /etc/ood/config/apps/dashboard/env
          subPath: pun.env
          readOnly: true
      - name: slac-ood-jupyter
        image: slaclab/gitclone
        #command: ["/bin/sh","-c","sleep infinity"]
        resources:
          limits:
            ephemeral-storage: 5Gi
          requests:
            ephemeral-storage: 5Gi
        env:
        - name: http_proxy
          value: http://sdfproxy.sdf.slac.stanford.edu:3128
        - name: https_proxy
          value: http://sdfproxy.sdf.slac.stanford.edu:3128
        - name: no_proxy
          value: .slac.stanford.edu
        - name: GIT_REPO
          value: https://github.com/slaclab/slac-ood-jupyter.git
        - name: GIT_RELEASE
          value: s3df
        volumeMounts:
        - mountPath: /app
          name: slac-ood-jupyter
      - name: slac-ood-desktop
        image: slaclab/gitclone
        #command: ["/bin/sh","-c","sleep infinity"]
        resources:
          limits:
            ephemeral-storage: 100Mi
          requests:
            ephemeral-storage: 100Mi
        env:
        - name: http_proxy
          value: http://sdfproxy.sdf.slac.stanford.edu:3128
        - name: https_proxy
          value: http://sdfproxy.sdf.slac.stanford.edu:3128
        - name: no_proxy
          value: .slac.stanford.edu
        - name: GIT_REPO
          value: https://github.com/slaclab/slac-ood-desktop.git
        - name: GIT_RELEASE
          value: s3df-dev
        volumeMounts:
        - mountPath: /app
          name: slac-ood-desktop
      - name: slac-ood-cryosparc
        image: slaclab/gitclone
        #command: ["/bin/sh","-c","sleep infinity"]
        resources:
          limits:
            ephemeral-storage: 100Mi
          requests:
            ephemeral-storage: 100Mi
        env:
        - name: http_proxy
          value: http://sdfproxy.sdf.slac.stanford.edu:3128
        - name: https_proxy
          value: http://sdfproxy.sdf.slac.stanford.edu:3128
        - name: no_proxy
          value: .slac.stanford.edu
        - name: GIT_REPO
          value: https://github.com/slaclab/slac-ood-cryosparc.git
        - name: GIT_RELEASE
          value: prod
        volumeMounts:
        - mountPath: /app
          name: slac-ood-cryosparc
      volumes:
      - name: linuxhost-adapter-src
        configMap:
          name: linuxhost-adapter-src
      - name: shell-app-src
        configMap:
          name: shell-app-src
      - name: batch-connect-app-vnc-src
        configMap:
          name: batch-connect-app-vnc-src
      - name: ssh-config
        configMap:
          name: ssh-config
          defaultMode: 0644
      - name: slac-ood-jupyter
        emptyDir: {}
      - name: slac-ood-cryosparc
        emptyDir: {}
      - name: slac-ood-desktop
        emptyDir: {}
      - name: motd
        configMap:
          name: motd
          items:
          - key: motd
            path: motd
      - name: ood-clusterd-config
        configMap:
          name: ood-clusters
      # general filesystems
      # kinda nasty....
      - name: sdf
        hostPath:
          path: /sdf/
      - name: fs
        hostPath:
          path: /fs/
      # support infra sw
      - name: munge-socket
        hostPath:
          path: /var/run/munge
      - name: slurm
        hostPath:
          path: /opt/slurm
      - name: slurm-config
        hostPath:
          path: /run/slurm/conf/
      # ood apps
      - name: ood-desktop-config
        configMap:
          name: ood-config
          items:
          - key: s3df_desktop.yml
            path: s3df.yml
      #- name: slac-ood-matlab
      #  hostPath:
      #    path: /tmp/sdf/sw/ood/dev/apps/sys/slac-ood-matlab/
      #    type: Directory
      #- name: slac-ood-cryosparc
      #  hostPath:
      #    path: /tmp/sdf/sw/ood/dev/apps/sys/slac-ood-cryosparc/
      #    type: Directory
      # logs
      - name: nginx-logs
        persistentVolumeClaim:
          claimName: nginx-logs
      - name: dashboard-logs
        persistentVolumeClaim:
          claimName: dashboard-logs
      - name: activejobs-logs
        persistentVolumeClaim:
          claimName: activejobs-logs
      - name: apache-logs
        persistentVolumeClaim:
          claimName: apache-logs
